apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prose-secrets
  namespace: prose
spec:
  refreshInterval: 1m
  target:
    name: prose-secrets
  data:
    - secretKey: PROSE_DB_URL
      sourceRef:
        storeRef:
          name: vault
          kind: ClusterSecretStore
      remoteRef:
        key: secret/prose
        property: PROSE_DB_URL
    - secretKey: PROSE_DB_USERNAME
      sourceRef:
        storeRef:
          name: vault
          kind: ClusterSecretStore
      remoteRef:
        key: secret/prose
        property: PROSE_DB_USERNAME
    - secretKey: PROSE_DB_PASSWORD
      sourceRef:
        storeRef:
          name: vault
          kind: ClusterSecretStore
      remoteRef:
        key: secret/prose
        property: PROSE_DB_PASSWORD
    - secretKey: PROSE_JWT_SECRET
      sourceRef:
        storeRef:
          name: vault
          kind: ClusterSecretStore
      remoteRef:
        key: secret/prose
        property: PROSE_JWT_SECRET
