apiVersion: v1
kind: Service
metadata:
  name: prose-funnel
  namespace: prose
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/funnel: "true"
    tailscale.com/hostname: "prose-api"
spec:
  selector:
    app: prose
  ports:
    - port: 443
      targetPort: 8080
  type: LoadBalancer
  loadBalancerClass: tailscale
