apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-blueprint-grafana-env
  namespace: authentik
spec:
  refreshInterval: 1m
  target:
    name: authentik-blueprint-grafana-env
  data:
    - secretKey: GRAFANA_OAUTH_CLIENT_ID
      sourceRef:
        storeRef:
          name: vault
          kind: ClusterSecretStore
      remoteRef:
        key: secret/grafana
        property: oauth-client-id
    - secretKey: GRAFANA_OAUTH_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: vault
          kind: ClusterSecretStore
      remoteRef:
        key: secret/grafana
        property: oauth-client-secret
