apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - unbound-config.yaml
  - storage.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - authentik-svc.yaml
  - orbital-sync.yaml
