apiVersion: ENC[AES256_GCM,data:GJU=,iv:menmSao9kN4Ez5fieVSmzfmVHFIK2o8lda2/C0jbWBU=,tag:mvUqtz6P6itK4hsmk9itmw==,type:str]
kind: ENC[AES256_GCM,data:DSWHaRAH,iv:S8d6IU30Bez7dc0zjDTxQwQkR7/Shub/J7EVdMr0b3s=,tag:OgVMK95csskEF6OsSr2mww==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uNxYoIWDj9lBXR/h/A==,iv:P9UqxnWLqQR4m7vu3+dPbLfHwHq/m+0QoAXtC+/NKqk=,tag:bQ0YIInFbHhvZeLl9sA9tQ==,type:str]
    namespace: ENC[AES256_GCM,data:+QMvVP8l,iv:8qFncnPcDGVd2WdY7lXzlgEVXavCyOpxAivn120vGDc=,tag:D2ScMk2IwaV0kWazUzeYfQ==,type:str]
stringData:
    webpassword: ENC[AES256_GCM,data:spbMjEO5XrxDJjY=,iv:qOZJ/d2fpP1/ZHooWo+F7TifVAAFKYRsxnQniys5m9k=,tag:ShDOBgqNRMLm2ggIeXxvOw==,type:str]
sops:
    age:
        - recipient: age1sl4vva0g5zsk5mp9dqqwh34t7vtjd5m9dfqdpwl9ete638939q3sckw036
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TjVvVG14cVJ2MXZIOVVo
            Mm1lM3lteW9JNmNUbTM3R0lrSnZjWThSakZvCmxxOTlGWTZBL0M4aUJhVU93bENx
            Q3JjU1RpZWdwZk1jci9QckFXeEdERDQKLS0tIHlmYy9Fa0xRSkl5Skc2dXVTd0Rt
            c1orOFB0aXdjekZzaWVaNmx5VER2ZmMKmIrgRtI/0mS/2RI786zKg8lpLHaJNV4g
            rYAtRZn608p+gEPnhz6QPK1Nsf299fJNsZsjLK3cFH8JfKZTAf5y1A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gqdkg7fwguwtyp6glxeln6chmusjye4k8yhe6kq9g7gch4lt45dqx5xtvx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVVFnK2xjR0czMGlRMGcx
            dnU1L2RwUnFMdEZFaXJCcDgzcUhTMU84UlFBCnN3ZVhlbkxnU29xYi9tY21WWDVB
            MC90RjR5WkVHMFoySzM1VkR3QkY0TWMKLS0tIDdVRTVleEREYmhDTFZUUExuSEJZ
            UTM1bDhmZXJCRHowMTNkdkp4V0pGTXcKtqWk8AoSkGbsIZFmWpWxTDtGsBzpX5PT
            ajlE8zhdndeEMN3k7JTT68UpzHUL51FejA+EZBOrf1vPKCHoflSU5w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l7adltmqwfdk663nazugqr3r65qknfc3q7jja6y2zv0mnekmg3hq2uekvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVmF1RlcvSTJlajdDZkZ0
            Z1V3R3F1YXRUU2xpbGJWK01ITExZSUVTNlhBCnpPd09TRWYzNmduU2NCaVNhU1Nm
            WXFaaVVtM1V0dWpOaHBsbzJzMHdkZkEKLS0tIG9xU2h0Q1RxOGpyUWZOWmxoRStE
            QXlqZDBVRUthcTRGK3ZZSnhxdjVDbzQK9Gu0bsEsg4UtuODxqyJ6I6IsNsE3F14p
            rchTEFUlpRy4RhlkkEUWVDzZODJ1LAv60/9IpSbJVYQvr1jPvjL4/g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kufgdtz7h7r40nl6wa55zgvxfzuc5sc3mh2qzthvfvz5l778hvjq6gxdjt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRXp1TUFaOW5RTS9ObS8v
            enozVTFFTG13bSt1NE1ySC90cUpZMXdSVkZjClF5U1o5bU1WRjFLVi9oaTBLSk1r
            RWN6RSswSkdBQTRkWXdtcUJvYVBGdTQKLS0tIG40OVZNakNWTFoxNHR6bjRhbnY0
            Y254eTFDUlFMSnBCV3o0ZGUyQnpMdE0KJbNrT0aYmIHzOfsVkehBh4ic3plKVlVY
            erRliVyAqlS+Xjb0cb1u5/PSvOBO4m+fysb4f3NUuUVvDBFJIBKZNQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age132hqe27z8z6t79uzsaxh6yfn2vnshvc0n0dmad53fss67tvhxcrsxuk5sa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYT0c2eTZPdmxQVllLTk01
            c1M0dUNlWGZUYUN1RGhKU21FV1doeE9UQnhZClArSUV2bVd3dXNSalRSajBIVlRj
            NkdzVXFYNTE5d2FRcEY1Tm5ESlp2dzgKLS0tIFp2cnVJeU1tU1dYbGFPYzdJTWt1
            VFpYZTdaZzFOVWcxTFVEdytpakRwUDAKygWUaQkxYII3bAFJkqhKd6v1HsGAq0v9
            PcwMudRof7884ZYDZ9/FnJh+bFJ1SPtvuqLmLvdowtEZENRpmJI7Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T06:31:22Z"
    mac: ENC[AES256_GCM,data:dfEqYLsupv9Phwt19t1VrUl7qiayUVzbBxmDfKgggh93LVeMnmE5r1IVbN6O+MPWgVAJPwTdQV2ol3EF6lBOyF+yS5/wE/dFDROgTzx9nScb9CAGEf6xya3RmaDSOXs4nIrK/nqSMPrXIVO9xaETxlzGwJJ4W08PLRSt9ml5s+4=,iv:BrIUfGTF1frr5hoJJo7mbjch+QROViWXi6/1iD5qqSs=,tag:DM5wNlYQBDhSSoV2dtPCZA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
