apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  target:
    name: authentik-secrets
  data:
    - secretKey: AUTHENTIK_SECRET__KEY
      remoteRef:
        key: secret/authentik
        property: secret-key
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: secret/authentik
        property: postgresql-password
    - secretKey: AUTHENTIK_POSTGRESQL__POSTGRES__PASSWORD
      remoteRef:
        key: secret/authentik
        property: postgresql-postgres-password
