apiVersion: v1
kind: Service
metadata:
  name: authentik-tailscale
  namespace: authentik
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "authentik"
spec:
  selector:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: server
  ports:
    - port: 9000
      targetPort: 9000
  type: LoadBalancer
  loadBalancerClass: tailscale
