apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: flux-system
data:
  TAILNET_DOMAIN: tail789d60.ts.net
  MEDIA_HOST_PATH: /home/anastasia/media
  REMOTE_PIHOLE_URL: http://100.113.161.17
