apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sewing-assistant-data
  namespace: sewing-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
