apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oauth-secret
  namespace: monitoring
spec:
  refreshInterval: 1m
  target:
    name: grafana-oauth-secret
  data:
    - secretKey: client_id
      sourceRef:
        storeRef:
          name: vault
          kind: ClusterSecretStore
      remoteRef:
        key: secret/grafana
        property: oauth-client-id
    - secretKey: client_secret
      sourceRef:
        storeRef:
          name: vault
          kind: ClusterSecretStore
      remoteRef:
        key: secret/grafana
        property: oauth-client-secret
