apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openpayrun-secrets
  namespace: openpayrun
spec:
  refreshInterval: 1m
  target:
    name: openpayrun-secrets
  data:
    - secretKey: ConnectionStrings__Default
      sourceRef:
        storeRef:
          name: vault
          kind: ClusterSecretStore
      remoteRef:
        key: secret/openpayrun
        property: ConnectionStrings__Default
    - secretKey: Admin__Username
      sourceRef:
        storeRef:
          name: vault
          kind: ClusterSecretStore
      remoteRef:
        key: secret/openpayrun
        property: Admin__Username
    - secretKey: Admin__Password
      sourceRef:
        storeRef:
          name: vault
          kind: ClusterSecretStore
      remoteRef:
        key: secret/openpayrun
        property: Admin__Password
    - secretKey: Jwt__Secret
      sourceRef:
        storeRef:
          name: vault
          kind: ClusterSecretStore
      remoteRef:
        key: secret/openpayrun
        property: Jwt__Secret
    - secretKey: MSSQL_SA_PASSWORD
      sourceRef:
        storeRef:
          name: vault
          kind: ClusterSecretStore
      remoteRef:
        key: secret/openpayrun
        property: MSSQL_SA_PASSWORD
    - secretKey: TS_AUTHKEY
      sourceRef:
        storeRef:
          name: vault
          kind: ClusterSecretStore
      remoteRef:
        key: secret/openpayrun
        property: TS_AUTHKEY
