apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - externalsecret.yaml
  - mssql.yaml
  - ts-serve-config.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
  - image-automation.yaml
