apiVersion: ENC[AES256_GCM,data:SeU=,iv:gZLtm0fZ5EaZ9OncHiP3GfJnoiHdSdUkQMXnXzSigGA=,tag:w5Aw+qkxhJfgMW7cXo2wHw==,type:str]
kind: ENC[AES256_GCM,data:JY/49m5a,iv:sLqPOnXmKLx4epDFszE2q14WjBMZyYhmKxZgPwme1t8=,tag:xHYnDobdps9SVQ5n676Flw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wibRnbDlGZdQSmHMVYU=,iv:kZy70Oh0dsmCVwy1vJN/lgDeJNYgPthJ7pu8y/pVOzc=,tag:XSxS8B+vI7n1mJyWVv6TIA==,type:str]
    namespace: ENC[AES256_GCM,data:FZq/POdod/0=,iv:ssWVlQzWtEdzRhtGcwPUYnUqWp+rADVZLhFiFxhzT8U=,tag:aMXV+UvzzafFbJRurVX3KA==,type:str]
type: ENC[AES256_GCM,data:egt4jS+o,iv:ObHO1NTHgtOmu8U2DPjtdRUVUMxeuwNYYAXkjDiUy1s=,tag:U2NmZKnkMqBYU+KERRhn7g==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:mGIFcRv/B4lKpacN6gJg5/OCtw7oRGyi5vOuSomGNO6kGgTIHFMpT6mrgw==,iv:nZjVZsQOjNfkuEaMuGrKaB3ar1H18YQi/mA/ODl53to=,tag:2bFLXKn9aWAhfwIau9v+zQ==,type:str]
sops:
    age:
        - recipient: age1sl4vva0g5zsk5mp9dqqwh34t7vtjd5m9dfqdpwl9ete638939q3sckw036
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYitrVjl6N0tIcVFEWmhZ
            T1krMFM0YTUxNnQ1N1VVZ3B1MFgvMkFwcVU4ClYzYUp5RCtQbkxlLzJzS3N6MSts
            T1dUSVZZVmU3NEpIV1AyWmo0ODJIVzAKLS0tIEpBWVBhZXAxOUtIa2tIQ2owSmQv
            aUwxSENQN05TQ0xKY3E5Si9vR2laSUEKJBMmQuRnPcfaVgihS6O8QNLMq9hg01Fn
            Np6MJ+HT8M+I/8uy5+47XwIQ3jvtcKT35PQnm/3S1nPw0bxeqQEh/Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gqdkg7fwguwtyp6glxeln6chmusjye4k8yhe6kq9g7gch4lt45dqx5xtvx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraHBkam9IcGsvcVUvc0VZ
            T0x4TkZmM1FIcTNSaXBlQjUwbS8way9CNUNVCjMrUDNDRE9pVFFGSUlrNXZrcmN0
            akVBNEZvdTRsaWUzQWFweE5IeE85TzAKLS0tIGdJdFlscm1jUE5rRkM4NzRmaFhh
            UmlySm5DRzgySnlmdk1RWDR5WmhUWFEKTLKNTGzA0/tcWYALRfIAaIgtPGi3M23S
            Bb+Q0GGDpfw5QZZunnnpFfhnPWGdMMg46gc8971sp14MEdMrjRm5sw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l7adltmqwfdk663nazugqr3r65qknfc3q7jja6y2zv0mnekmg3hq2uekvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvL0lzaFBiak9VTTZKdnJs
            TU5vbU1jUjhoZ3RVdGZCY0ptMGxKc2hIWlFFCjA5NFdsY0FicDlWaVlxUGxBTHhV
            a2EyOUVjOUFSWkxjb0dDS0R4eDNGM3cKLS0tIGFxakxrVTVSQWVkVUJXcUM4aUVD
            MERBQmZDMDNLUXBrWktrUFkrVHhmZXcKMr3YYCVIDukcfUsR7mzC0ciOas5xmwCw
            /EeYA+rCsVd64IvRqmAIi4bb5Ex8gH5uoO5dx7uaRVilgDyS4+4Wvw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kufgdtz7h7r40nl6wa55zgvxfzuc5sc3mh2qzthvfvz5l778hvjq6gxdjt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SG1PUjZrU0Z5MUR5NktD
            M2ZJZG41U1NEWXZPVXBqOHFkcDNDRFpiS1drCnU4MDZRWDgxMXlVYWhEb1dJeXZO
            RjY0OWk4alloS3ZRT2MwcDJLMVU1Y0EKLS0tIHd6YnVxcXF2VEtGM1hYeHRaUDlv
            TStTN2RtR1ZCU2plNFJQNUNTdVFYUTAK2Ej9WdthtsL+fnkiY7vTHlQGp4w1vlQJ
            o+o9yt1/XrDajDxwi0tVQT5EccuKzVvGWzuzmrQ9wt1NcnQJWJfw4A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age132hqe27z8z6t79uzsaxh6yfn2vnshvc0n0dmad53fss67tvhxcrsxuk5sa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ekhEcm9zOHJNb2xEWkJj
            SDZWbWtxck9UdFYzLzdNVjByRklRVGVzRzFFCllUNEFQdy91OEdSbVUwakVWSy9Q
            dVg3dTM1S20wRWVpeEltb1N6dU43cFUKLS0tIHR5WjBVeFgwUCtzV3NoVXlSUmtJ
            TWlFZGRjZGVnNU0vSTJ3VEp2MVdoZG8KQ7mlhXPfk6eHiXL97KwDm5gaL1KZVLTf
            RnzCwcrrzg+umke9EsHqTBnvqhI5fCKL+hnsgFWwMg2Scip52zgvCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T23:38:53Z"
    mac: ENC[AES256_GCM,data:PNWdblMXiCupjZ+QFsj+sCtaoTJwBCC5ZWJeXBhvg3C+TmjTH6SSrl8Pn5m1gEwiyVADwK02A+hk9Lnp2RTVz258viq27E77cqeP+pAJG+1SlWuS5ByqvIIcvoUBbQZrA8/wEYcS2DcLoOM4fBulXOw5zMcRG+jxjBixcJ2nUvA=,iv:zyEwVpVXM6RYbjaPZvfbk32+eRAxX7jECOQTmYOlqZQ=,tag:PRPKNXTdrYIkb7Y0WsJWqA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
