apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-secret
  namespace: crowdsec
spec:
  refreshInterval: 1m
  target:
    name: crowdsec-secret
  data:
    - secretKey: enrollment-key
      sourceRef:
        storeRef:
          name: vault
          kind: ClusterSecretStore
      remoteRef:
        key: secret/crowdsec
        property: enrollment-key
    - secretKey: pihole-api-password
      sourceRef:
        storeRef:
          name: vault
          kind: ClusterSecretStore
      remoteRef:
        key: secret/pihole
        property: api-password
