apiVersion: v1
kind: Service
metadata:
  name: vault-tailscale
  namespace: vault
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "vault"
spec:
  selector:
    app.kubernetes.io/name: vault
    component: server
  ports:
    - port: 8200
      targetPort: 8200
  type: LoadBalancer
  loadBalancerClass: tailscale
