apiVersion: ENC[AES256_GCM,data:tfs=,iv:JYu+46KNOgI5upElr+xp89ddr6OJlKonXZhiPmOGykU=,tag:mZeLFzzYPNw7liAPnPxf7g==,type:str]
kind: ENC[AES256_GCM,data:y/AxdQVh,iv:NWG7+vmc7jV4Qrq/Vza5Cai4rAlvtALDy4e6pP42V94=,tag:98XOIDiSR7lew83RAlqMqQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:WAh1C/PQ8RLYjeqh43JCJGg=,iv:SDb7Btefbzj8Tx6uQnX/9NoploIXtvS+kZnG2em0RnY=,tag:ouln4mGJz4erEAiYktgjlw==,type:str]
    namespace: ENC[AES256_GCM,data:viGTdFY=,iv:Ma5qEmNK191OjpWv2mSL6H3MTPv0cNc3no/HkxcTxB0=,tag:B0E23VkxkurcvhY2SebArw==,type:str]
type: ENC[AES256_GCM,data:BTxKac/g,iv:FiCdStExWteEavn0pl5QtuFjml4e3fdzXYxtSfILYAk=,tag:xv/uguMILMnsCw1neut7aA==,type:str]
stringData:
    key1: ENC[AES256_GCM,data:NdqiO2Ide8E6LMy7mHYmNK7IrD9y28wY6axbwtJIdthEooN4u/sW+KTtfvE=,iv:bA/OStOJLk3oQPTWsDZGtJsPvoraYhIvhdMUGUjSZvM=,tag:CY2cmOe7fW+qHt13C+iI2w==,type:str]
    key2: ENC[AES256_GCM,data:Zy+YDJsWf3JLnnOWAzPe08qdQ5E4vc26/Mbn3k2az+2HDfsFx3b6HH+gTpc=,iv:VRBF9b+OTib+c+AVV7lkEINdn8H80PpP7DgWrkNsp2s=,tag:fobLCVoEoSwCXJZcDH+jTg==,type:str]
sops:
    age:
        - recipient: age1sl4vva0g5zsk5mp9dqqwh34t7vtjd5m9dfqdpwl9ete638939q3sckw036
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwenlueGpFWXliZWRqNWd6
            SFVqR05vQUlibWxjMU5VclpBV3F1MWN1Rm1RCnY2dk0yN205b3M0RG1vZ1RJa0xi
            dklpMU5DNTV1YlAzdkhKcEdlbTRyVUkKLS0tIFozMlQ5dTl5eUw1N2pLQVVYM2dt
            VjN2Q0Judm4xL0dLbXNtMFd0TU96KzQKbirPVzushBR8zbFzp7XGexdVbmSd6lph
            vBNSG7p7xd6jKbKSGQSQpfdpDvVULvRx/OZcL3cPQ48X/fH4wRxugA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gqdkg7fwguwtyp6glxeln6chmusjye4k8yhe6kq9g7gch4lt45dqx5xtvx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WnFJWFA0MWxJVHFJNEls
            ajg0K1BaZDF5ZDVLdWgycDZlZE1Zc2NUSVFZCmJFQmxZUUE3dTk5SnNkR1hHVkR5
            NWtGTitlUyt2LzZBcjdSRHZ6cXZOUkkKLS0tIFQ0QVp2d1JkcGFUN0J0SlZEcHkz
            bWNGYXYzTFVGTHdlV1JkWGhBMWgzaVEKi1CH28e60K+aGBS3yoRwgfHVPjO1PfXb
            N8evC/plezSHkaGbXVrDSbDHJ87hKVwavPAXrjlyrFUiSADFiqxk6A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l7adltmqwfdk663nazugqr3r65qknfc3q7jja6y2zv0mnekmg3hq2uekvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdHFkNXI4bmJKYU1Fb3ho
            SUNya0ZIUzF0ZGJwdEx2bXMzVDVTd3prOEc4CmxTalUrYU44Uk4xU1pzTmcxZVd0
            MXdGV0NZdDF1Z2RSQVk2SzNsRHNBd1kKLS0tIDF2bkI2UkRhc0h6UjFlUTZNMmtS
            R0hpZDd3Y2ZNcTFHbnNXOGVGckMyTE0KZYBu1F2EaqpFCbTmbKo+APU3QQsl7Yil
            WF0ld9k4PnvdkfcMKZRbxk9sQAh3ixSpNBKG1q6/LX3MtVh3akQ3fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T01:52:10Z"
    mac: ENC[AES256_GCM,data:nGoB4pP1VANPfpNH8pqRE/R0iKWJbG8YvRnHr1FiM/GfvKYGcAfMoMxtXvC/OTBTYROVTZ7dq9ZtfFps9Q59+LR5P4xzZJi6XMxWGX1VvVYbB1sZIS2dbSKaJdUOfSYb9ROJFz80xB6u5BpGU8J6saSOGI9dH1sVZefbj2Wy/bg=,iv:6IoyKiValbmLEkdHpd094tr6AeJoodU8hyUQUOD4mtk=,tag:15ipTP+Xo54f5Ld3qZ4rVQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
