apiVersion: ENC[AES256_GCM,data:QJE=,iv:28nIcWUoKx/DjL4uuSyfKpesU9tEZXGEga3ZWjqDzIc=,tag:yQmmDLkMvpUagCfOvOSyxA==,type:str]
kind: ENC[AES256_GCM,data:LsVWCA+x,iv:QP6dgeL0enMuXffwvokPek8GB6MFiBebmV9dO89Skes=,tag:4nsV9dCI765umeOj2DpShg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VfWLpLgSxuWy9RP8uiaZSQvVA44=,iv:3M6SxlfvSn5fe8+TkGnfrK9FE03LOT7NXsa5/0le0ts=,tag:Jn/JPCmX5Ify3b5CIrnjbg==,type:str]
    namespace: ENC[AES256_GCM,data:8beuJtvUZqq9iA==,iv:2Q6DWN6pt/dLugfkjGh5OjELb3oPUDNBt6qGNPZWDBA=,tag:sz0hiTtspgBUHXYfdFihcw==,type:str]
type: ENC[AES256_GCM,data:ColZdm/u,iv:N543U2aQyMJi1cZDsdy8XpKANFfpHKTLRtpUxtbtX3o=,tag:S6sgchTDm5K2dokN9UMjpw==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:8zug4b0=,iv:GKX3py5RrIKZ/eDHd/IXM+WvBUMnWAu6vIUIBooNeGQ=,tag:LxOgQAkuqPno04dOk7cgqw==,type:str]
    admin-password: ENC[AES256_GCM,data:0UY1KKb/dMNlw5ctlPq8+ICQ/Nm20Q==,iv:JYiRfeuiz5Ou+UNrLcgt9Y+GUuorjkKvTEJS0KdSDKs=,tag:7/jJ/LMuGjlMmkZhF3eGgA==,type:str]
sops:
    age:
        - recipient: age1sl4vva0g5zsk5mp9dqqwh34t7vtjd5m9dfqdpwl9ete638939q3sckw036
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWnFaVVRaVDJmWHJvdDNW
            TUw4aTZYcU9BWDdQQTdEdkJHRm1YeGZVR0ZrCkU1Yk5hWE9qbnE3RE5wZXEvQ0NW
            a2dTT0FxVHVybHI2VG5samZzdGQ0S0EKLS0tIExjZ1hQaVhsaENnTmE3dzFoK05K
            VG4xTy9HNXBjUThTTmJGMnRLbHRHQ0EK7ZTZG6zX0uPh05yDWOq9BXWfoOSB3/EY
            DjG9MD0rH2ne43xnXU/6EaCnikYnKJ5PnL+A6OvMujRc88pTOZLIxA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gqdkg7fwguwtyp6glxeln6chmusjye4k8yhe6kq9g7gch4lt45dqx5xtvx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISkpFUGVST3FoTnp5S0pi
            VHVtTnpBbDFDOGpnYWNoSWt1ZDZkaFlPVWdjCjg2NTJMWFc4SXVtZzJ2YzFxOWtS
            eE52RkIwWStnNE84cGJoYS9SVXpvVFUKLS0tIDlNbExpd0QyOU5sTStBeUlIMlRy
            eHlDeUljblNnK2hWN2dmWUFEZzZCeTgKfLv1J0MaWrYSxJr3cwM/T1dyLdQd0e3g
            qYOmGoU69pU379S92UMsMCc1VM/v+js4ervxGHEyuvxOhsTSMOz7iQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l7adltmqwfdk663nazugqr3r65qknfc3q7jja6y2zv0mnekmg3hq2uekvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTVlGai8wNlZ4UDJJSVdB
            SlJYQkxTUnR3blU2UXpwYXZNTGZzUVNkZWlNCndCR3FWdVgxaTBjQ3dkRWRmdHBw
            NkdCSUJodStjbVFNanN6UVpaUHQyc1EKLS0tIEJHV2JjcFpQT1BFa3Y1eE40a2c4
            Y1h6eXgvTVZHNkZDK2VqbU1aQnYrZHcKBVKXqBrB76m2UpOlaFlPdkDh/xR3nAsE
            pGKq3IO1PMTpBMMAKhKVp182fuSFdg7RDrbAri43JnfTdHcQ6Jjz0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T02:21:15Z"
    mac: ENC[AES256_GCM,data:DCSdQua7KP/TgSe/vjOgWuUrfvkCnWRybiwLMxM9TkUK9svDyQjcJdA2WopBqCsRMyHiOvdQEW49qn2QaFW3npGRfFAbNNU8DGiFURDuocF6eJwoTIh3SJdsl63rt2bKWbyVPgxonRj61bvntgbfk0TWZsQ985aGHvw4ikxy+OE=,iv:x1zzC08nvn81sI6H8XmVp/kfGtYaxUK3pFHEm+moDuY=,tag:ozLggcW85Xb21GtZo6aMNQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
