apiVersion: ENC[AES256_GCM,data:QhNo3P8s26t6FwpUwmwTkebsfLQj2WVFMg==,iv:rqsq1k0JHB4033Z6125ZAZHqA3mjFSeqF9MgVZpRXeY=,tag:pqBWzNwZobmeIReH27DZzw==,type:str]
kind: ENC[AES256_GCM,data:acCGvpSvJPuQwM8=,iv:9/6CJqi7nfToJPOXs2hMM5B10mx2ANjanqMcOPfBOkk=,tag:8Bv0k3Bs/iS7EOi8KPViiQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:umleIAHO12v7XknHMPIi3h/XFqHd,iv:gxYCaErRIhXVIi8YdifJVfnW2sA5BFwTv2W2rZgsJHQ=,tag:UYcy5MPvyHfeLlWyplspQQ==,type:str]
    namespace: ENC[AES256_GCM,data:05hvCwf4wzw0Xw==,iv:Z35X4CP8nTLaQd659Ruow2nNoeSDo/2LlE2VDvZZTWY=,tag:f4ZAoj80AfoMVeAWiOlcjg==,type:str]
spec:
    interval: ENC[AES256_GCM,data:6Yk4,iv:nteWwcS0zRwcWXNySkcsdiM8bOgwPqFZhGFG1TIiaDk=,tag:W73dVDBXK2+JdhYY97EY5g==,type:str]
    chart:
        spec:
            chart: ENC[AES256_GCM,data:j9Yq2QwFORtVI70WkrLCcQYk4n6e,iv:PvJsK345ZvjYdQABpUDQGKDg8qEa9UVhyiRauELZEkA=,tag:tE4sQCYjzDPFqG8bk/4MCg==,type:str]
            version: ENC[AES256_GCM,data:QxHvCFUHlg8=,iv:vXJRRApZLKO3djxdP30wtcOW31pMRuPYIVlSiocBAII=,tag:vgA6N/O9LB5TLTPR7LzYqw==,type:str]
            sourceRef:
                kind: ENC[AES256_GCM,data:XeuXeNMRu+4xcd4ML7Y=,iv:cZ3/q5TYwwGShyhxbjCdNP2FrbEMLqmZG70jIsZJBcM=,tag:xID02R194cCQHpCI83mkUw==,type:str]
                name: ENC[AES256_GCM,data:sd+/SZv0DQvtA4taa3AK9c3zsBk=,iv:D1OEs73//LwyU1xM+pjhz0K9SpQTbK8vCJXfDsa7Ge8=,tag:qYVvuCCXDHIJbjl7qn7j6w==,type:str]
                namespace: ENC[AES256_GCM,data:GQtZS9VTSpls56A=,iv:d+ukWEsE5fueVhEZt2uQdt9V5RF3qv29ZLlwHts7XRM=,tag:RkYfYuCBmPd421lhmflMUA==,type:str]
    values:
        grafana:
            enabled: ENC[AES256_GCM,data:4EVqxQ==,iv:2cVlYVIWSepS6Z/58FSEhrBgBHCos79Se7FI3OrL9F4=,tag:8UPRMVOCsbZm5QvKsc6ouA==,type:bool]
            admin:
                existingSecret: ENC[AES256_GCM,data:ZS+gKpDp2rk1z09rjQmD7ARFgxE=,iv:3XrNud8Kq9JRaF5QBrsRmLuB1oyefd9uqJK4tyEgVBw=,tag:g36wlqKMfXqrRF/cO9B6xw==,type:str]
                userKey: ENC[AES256_GCM,data:RomNhqav0v+MEg==,iv:7Hc+CyNJLlLL2JxjF5ZeQlfvKeOwjRIMPp4hzs2TTgg=,tag:bGR87QRvxfevHBw4ZTT9zg==,type:str]
                passwordKey: ENC[AES256_GCM,data:rzuUMxhCgWtFV7+MR+0=,iv:pUKKyUpLKReXGxuHIcS2TddUqhdJ9qh0P1CqBWu+eFY=,tag:pneMDugXQVFatJEGNhrGKQ==,type:str]
            env:
                GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:KQiqHgisfAiDmAJRAH0wPjsO0P2ho4m8mx8q6kH8M2kManbrnOf64Q==,iv:qLRtYrpvM9/FI9m1Qm2bOO7opYprxlpjiUvQyCMCsoU=,tag:Fp7KiPWt2va2Bw4Uo1lVbQ==,type:str]
                GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:jhtgazgZfSfr+8kf0PCUH+0gg8T3/hLRpRECq/cRL3iomGRTpbFOQoNbJdap1bL5q+db+ekZpA6l83q5UcYJ5XVTmHsVJ/hN2fSb5LpSvHMWPorvia4qNUlffYgnW26k1busjMxDGv6th2wC4rLtGEuoPqVqQ1zeBlotnKk66h8=,iv:x0+SjWzcNa1bih0z9tGpnN32PZ4hDixcYeTvsgbTL+k=,tag:rcLzt1vcfo2jd03PUc+Eng==,type:str]
            grafana.ini:
                server:
                    root_url: ENC[AES256_GCM,data:P1RBt84JNP/fYIgfb4eJNKXhB5JLOlC8PfYeQ1ItBBk=,iv:tUthZJkKKeNYaKO0Iv69wZKKxRCE7MMA5nKaFFPEvzE=,tag:lZgdhtFdf2SfaGqp/N3kmA==,type:str]
                auth.generic_oauth:
                    enabled: ENC[AES256_GCM,data:iOtTEQ==,iv:9mBsL7NUXt6bDvXYYnsmR6/qq2TSTC1RcS2H7hwMEjQ=,tag:X72mV+X/MLddN2Xnt8JlMQ==,type:bool]
                    name: ENC[AES256_GCM,data:Syx+cJACtrYG,iv:9zBoPEbPrZfl38AFKvvMn2s1zPGDaU1nUqRkxfhYsZI=,tag:cdMzf8vw+vUV5K/zCpsUyQ==,type:str]
                    allow_sign_up: ENC[AES256_GCM,data:KkhUgw==,iv:MVPB18OpcNSj9oeSWfE3f2h+M3XuubUWZfvSzEbEjeM=,tag:l5ONcFMvPezTVF84/46ucQ==,type:bool]
                    client_id: ENC[AES256_GCM,data:QaW3tjozNvObxbXfmpQr8I2BU5sLvM6ZvHRb5VSmJKJIYtXord48,iv:TVMsW6W2sxCxhCcERMM6oTsdP3VBzE/s6h/CF1QTvQE=,tag:6EDZfdA6KsKk9eRJtpP9Lw==,type:str]
                    client_secret: ENC[AES256_GCM,data:kGCoepcrVi7PxnH1yUIv29TwzsULfCU3SmDXKNaTK7aeseSRHA7wZfHNzg==,iv:3858UfqcpfjoDUHqnOx5W4uYDiYMyv5uZ8/GSQZ//y0=,tag:Pshlh5XI+f58UfQaCDcQnQ==,type:str]
                    scopes: ENC[AES256_GCM,data:tOUwNKg66M2rsccbHYmIgQaNMpA=,iv:OFiChHKaiAypc1X+qlktrzKL717jl3x+ampwsjn/Pt8=,tag:Nm6wDLCYWQkH+yUQWniylg==,type:str]
                    auth_url: ENC[AES256_GCM,data:9Fs9cnoXnoZkJLZJlwRqlHysSx1wmTJFs5Zf5GkPAv3yG4QJ3nnpzcxO9ACXSbOSoH9ohqALm+06jqeUPXUfdQ==,iv:AqTuzyDL9mjl3zaBwnNBbFAdbviMybdeCbLex5vffJ0=,tag:8aKlKTOxgo/y2kT++kwO2w==,type:str]
                    token_url: ENC[AES256_GCM,data:2hgjXTFM++Tb5PO324cAjpJSCmTQ0NRxnR3BhCMPihUSKDyOJU0Iel3XopZjFoEI/YSXWAR6V4dQjm6e,iv:MyPUn64ltKbdZBTv9J2srBJksg40izr5Q16bpvrtM1I=,tag:PawU9uAH9YmpcSXsyUdCyQ==,type:str]
                    api_url: ENC[AES256_GCM,data:WY0JJSInh52723m2wZ33FTJJmkjEcY+sC2VIVcV8h5/L7XT7FBAjXa4j2tHFVnH+vsahi71xgzqvc0ssfkmh,iv:TJbsdWu+yUdMCLM9/whHNa1EKg5VHgINdbn3/SkeQX8=,tag:sljn1qCtQI4p8Y20NhqKEg==,type:str]
                    role_attribute_path: ENC[AES256_GCM,data:zKcoN6toB+kRqkvOojMMtCqP/QbMMyKA2HMgiZ9eNbVGwlMXP6N/id1T8PjjKWBFHOIicSyK8vIR/qY=,iv:g0Wu0WcaC7dHKzptb/bpPNrdHhUnjzd22DE96NIP60Q=,tag:pA+6x+/9J6FnVTNLmu7KDQ==,type:str]
        prometheus:
            prometheusSpec:
                retention: ENC[AES256_GCM,data:LmlM,iv:RrtXSRL3Z6iy+p617sWKjSLG2lp2ENz/MlwKliBXla4=,tag:fKwW0VIsAqjBvzEslxmJQQ==,type:str]
                storageSpec:
                    volumeClaimTemplate:
                        spec:
                            storageClassName: ENC[AES256_GCM,data:86k4rMU/Bvl0tA==,iv:RHQemQZOQHydop+bTbxmyF7WUhr+H66omQlH6RVP/OY=,tag:v54EdKnmwgz1fAkuWYwPXw==,type:str]
                            accessModes:
                                - ENC[AES256_GCM,data:noOyZ6PBkrBdVP4mlA==,iv:hLLNWyUlOiNzurPPLtXkKTt383+6Gs8iYX8VsCQXuZA=,tag:mmFNDdySPlK6wgeLiSSPlw==,type:str]
                            resources:
                                requests:
                                    storage: ENC[AES256_GCM,data:i0x1BQ==,iv:N5cZzwwCZtowBry8awq1CnIVbYxWlAvwvLgiAEtmdhg=,tag:2u1QxlNf7avf7b6UGLlggw==,type:str]
        alertmanager:
            alertmanagerSpec:
                storage:
                    volumeClaimTemplate:
                        spec:
                            storageClassName: ENC[AES256_GCM,data:KlGAbuw9vWHg8w==,iv:BGBYmPEAgRclBybVDOonrFRRrFIsDQPOeZ5kDwE518g=,tag:QHw2IVaEeJk2qYHIXVEUwg==,type:str]
                            accessModes:
                                - ENC[AES256_GCM,data:q1uyFLpAg3Fh5XwMkg==,iv:TBy4o7FaUkwZE6V6OzkzqsBqP+Tljsj3m6kswsOhG1U=,tag:MmsSIYF7DRwErfrcoku+Yw==,type:str]
                            resources:
                                requests:
                                    storage: ENC[AES256_GCM,data:us1U,iv:EDoybsW+cOvReTXX8V23967ih7lRHTIzQTXh0CxbmGY=,tag:wmEgd9A8KWkYf+tHfVzaWQ==,type:str]
sops:
    age:
        - recipient: age1sl4vva0g5zsk5mp9dqqwh34t7vtjd5m9dfqdpwl9ete638939q3sckw036
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBReU16L1JnZk1PMjJYbXBM
            TFY1K1c1ZDdKUDFFamJOdWsya0FnVlV2bkNvCi80M2VZcmFOMW1LS1ljbG1TV3BK
            cHVDak9kcTdkeHlkNlN4ZEtGZXY5TDAKLS0tIHF1SEhQSjZhRHU4RXhJMmlvMWRP
            VEhIZ0pJTjhvVkRBTlBOVEpRY3lUbzAKgcmZzNj4s5U9ZCN30yvaiSEZ/5d0mPMM
            xCEplT0f+lY/ca269KF44E0gNIUqTscuHs6d1QsWtzNNvWgcG2NJfA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gqdkg7fwguwtyp6glxeln6chmusjye4k8yhe6kq9g7gch4lt45dqx5xtvx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYU5qSVhWMXJXVHd2Zm11
            SEptVWRydFVFZDFSTUNLTjNhZXFKbUVnbVVVCm5IRFBlZGNPMndYVkU0OStVbkVS
            bUNka3FIYXFDVjlzY2lhVUVod3M1ZWcKLS0tIDFLdi9zTDhHR1V6RzRKVWVWZnFC
            eEtCUSsrbjhyV2Erd0JWKzhscElzRzAK8ymKb1g3L2VGi0QqsFwyM+Czz3YTE0FL
            OM5mGdMtpGz2xTjlaavvVDs3CyOBTtOEXP3gNVr7ctXaCg2itaxV7Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l7adltmqwfdk663nazugqr3r65qknfc3q7jja6y2zv0mnekmg3hq2uekvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSDlFV1ZMMmkyRHVnRFdG
            MytKTU1IYTNCVXdSd1VwdEZJdDAvbEtrbnpzCmRkUzVqT1oxSUg2Qmh5NEEyT0RL
            LzR1cFNrSkNBNCtSLytwZzdNQXpGc0kKLS0tIFpZTVI1UUJiS1hWK2RUdVVzYW03
            RzNHZS9FNGdUWkdFb01IQnh4cGx1VzQKs0eS8BJAt8z53blGCokRD5NLmmAVAJG1
            Xur4qkbtDuC0CXhPFOavjaZNmG3AFHjTLoj3my0XMwsBP1gDXHjKCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T11:05:54Z"
    mac: ENC[AES256_GCM,data:GJjigWhpptse9ypqogphf6yaeiOy3DGWh6qL/2vvv/lrYLM4EznNSINo8aX5G6WmaJPHxmkOtCwqdduToK8MnuB9lvvbv533IOMmGsZVzhnGDg8vMehS5Ct1SLk5Qn7da5qNIu896AxmGPq9ESDLdg3I7q4+150apgrWTyADTBM=,iv:jsBYvz+Ch9ydgcdhbjAAgFEFyiygKS5xZrgOvimRGKM=,tag:VP4E2Bc9FOCPdAwrTQZykQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
