apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: tempo
      version: ">=1.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    persistence:
      enabled: true
      storageClassName: local-path
      size: 10Gi
    nodeSelector:
      kubernetes.io/hostname: asta
    tempo:
      storage:
        trace:
          backend: local
          local:
            path: /var/tempo/traces
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
    tempoQuery:
      enabled: false
